device:
  location: "/dev/usb/lp0"  # Path to the printer device file

format:
  special_chars:
    "é": !!binary |
      6g==
    "—": !!binary |
      2Q==
  unsupported_chars:
    - "~"
    - "`"
  max_line_length: 78
  lines_per_page: 60
  line_ending: !!binary |
    DQo=.
  page_ending: !!binary |
    DA==
  bell: !!binary |
    Bw==
  underline_start: !!binary |
    GxszbVs=
  underline_end: !!binary |
    GxszbVw=
  bold_start: !!binary |
    GxszbVs=
  bold_end: !!binary |
    GxszbVw=

api:
  port: 8000
  host: "0.0.0.0"